version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
    command: "poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  worker:
    build: .
    depends_on:
      - redis
    command: poetry run rq worker --url redis://rq_redis:6379 order_queue

  redis:
    container_name: rq_redis
    image: redis:latest
    ports:
      - "6379:6379"
